<a href="https://colab.research.google.com/github/hatimdeve/python/blob/main/Encoding_for_Multi_Categorical_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
from patsy import dmatrices
import sklearn
import seaborn as sns

In [2]:
from google.colab import files
import io
uploaded =files.upload()

Saving train.csv to train.csv

In [5]:
import pandas as pd
df=pd.read_csv(io.BytesIO(uploaded['train.csv']),usecols=['X0','X1','X2','X3','X4','X5','X6'])
df.head()

   X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

In [6]:
df.X2.value_counts().sort_values(ascending=False).head(20)

as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
k       25
i       25
b       21
ao      20
ag      19
z       19
Name: X2, dtype: int64

In [7]:
top10=[x for x in df.X2.value_counts().sort_values(ascending=False).head(10).index ]
top10

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [12]:
for label in top10:
   df[label]=np.where(df['X2']==label,1,0) 
df[['X2']+top10].head(40)

    X2  as  ae  ai  m  ak  r  n  s  f  e
0   at   0   0   0  0   0  0  0  0  0  0
1   av   0   0   0  0   0  0  0  0  0  0
2    n   0   0   0  0   0  0  1  0  0  0
3    n   0   0   0  0   0  0  1  0  0  0
4    n   0   0   0  0   0  0  1  0  0  0
5    e   0   0   0  0   0  0  0  0  0  1
6    e   0   0   0  0   0  0  0  0  0  1
7   as   1   0   0  0   0  0  0  0  0  0
8   as   1   0   0  0   0  0  0  0  0  0
9   aq   0   0   0  0   0  0  0  0  0  0
10   r   0   0   0  0   0  1  0  0  0  0
11   e   0   0   0  0   0  0  0  0  0  1
12  ai   0   0   1  0   0  0  0  0  0  0
13   e   0   0   0  0   0  0  0  0  0  1
14  as   1   0   0  0   0  0  0  0  0  0
15  ak   0   0   0  0   1  0  0  0  0  0
16   e   0   0   0  0   0  0  0  0  0  1
17  as   1   0   0  0   0  0  0  0  0  0
18   m   0   0   0  1   0  0  0  0  0  0
19  ak   0   0   0  0   1  0  0  0  0  0
20   m   0   0   0  1   0  0  0  0  0  0
21  as   1   0   0  0   0  0  0  0  0  0
22   a   0   0   0  0   0  0  0  0  0  0
23   m   0   0   0  1   0  0  0  0  0  0
24  ak   0   0   0  0   1  0  0  0  0  0
25   m   0   0   0  1   0  0  0  0  0  0
26  as   1   0   0  0   0  0  0  0  0  0
27  as   1   0   0  0   0  0  0  0  0  0
28  as   1   0   0  0   0  0  0  0  0  0
29   m   0   0   0  1   0  0  0  0  0  0
30  as   1   0   0  0   0  0  0  0  0  0
31  as   1   0   0  0   0  0  0  0  0  0
32   m   0   0   0  1   0  0  0  0  0  0
33  as   1   0   0  0   0  0  0  0  0  0
34  as   1   0   0  0   0  0  0  0  0  0
35  ai   0   0   1  0   0  0  0  0  0  0
36  as   1   0   0  0   0  0  0  0  0  0
37   k   0   0   0  0   0  0  0  0  0  0
38  as   1   0   0  0   0  0  0  0  0  0
39  as   1   0   0  0   0  0  0  0  0  0

In [14]:
def one_hot_topx(df,variable,top_x_labels):
  for label in top_x_labels:
   df[variable+'_'+label]=np.where(df[variable]==label,1,0) 
df=pd.read_csv(io.BytesIO(uploaded['train.csv']),usecols=['X0','X1','X2','X3','X4','X5','X6'])
one_hot_topx(df,'X2',top10)
df.head()

,X0,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,X2_ak,X2_r,X2_n,X2_s,X2_f,X2_e
0,k,v,at,a,d,u,j,0,0,0,0,0,0,0,0,0,0
1,k,t,av,e,d,y,l,0,0,0,0,0,0,0,0,0,0
2,az,w,n,c,d,x,j,0,0,0,0,0,0,1,0,0,0
3,az,t,n,f,d,x,l,0,0,0,0,0,0,1,0,0,0
4,az,v,n,f,d,h,d,0,0,0,0,0,0,1,0,0,0

In [15]:
df=pd.read_csv(io.BytesIO(uploaded['train.csv']),usecols=['X1','X2'])

In [18]:
freaquency=df.X2.value_counts().to_dict()
df.X2=df.X2.map(freaquency)
df.head()

  X1   X2
0  v    6
1  t    4
2  w  137
3  t  137
4  v  137