<a href="https://colab.research.google.com/github/hatimdeve/python/blob/main/outliers%20detection(z%20score).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas  as pd
import matplotlib.pyplot as plt
import numpy as np
from google.colab import files
import io
uploaded=files.upload()

Saving test.csv to test.csv

In [2]:
df=pd.read_csv(io.BytesIO(uploaded['test.csv']))
df.head()

  gender     height
0   Male  73.847017
1   Male  68.781904
2   Male  74.110105
3   Male  71.730978
4   Male  69.881796

In [5]:
df['zscore']=(df.height-df.height.mean())/df.height.std()
df.head()

  gender     height    zscore
0   Male  73.847017  1.943964
1   Male  68.781904  0.627505
2   Male  74.110105  2.012343
3   Male  71.730978  1.393991
4   Male  69.881796  0.913375

In [7]:
df [df.zscore>3]

     gender     height    zscore
994    Male  78.095867  3.048271
1317   Male  78.462053  3.143445
2014   Male  78.998742  3.282934
3285   Male  78.528210  3.160640
3757   Male  78.621374  3.184854

In [8]:
df [df.zscore<-3]

      gender     height    zscore
6624  Female  54.616858 -3.054091
9285  Female  54.263133 -3.146027

In [9]:
df[(df.zscore<-3) | (df.zscore>3)]

      gender     height    zscore
994     Male  78.095867  3.048271
1317    Male  78.462053  3.143445
2014    Male  78.998742  3.282934
3285    Male  78.528210  3.160640
3757    Male  78.621374  3.184854
6624  Female  54.616858 -3.054091
9285  Female  54.263133 -3.146027

In [10]:
df[(df.zscore>-3) & (df.zscore<3)]

      gender     height    zscore
0       Male  73.847017  1.943964
1       Male  68.781904  0.627505
2       Male  74.110105  2.012343
3       Male  71.730978  1.393991
4       Male  69.881796  0.913375
...      ...        ...       ...
9995  Female  66.172652 -0.050658
9996  Female  67.067155  0.181830
9997  Female  63.867992 -0.649655
9998  Female  69.034243  0.693090
9999  Female  61.944246 -1.149651

[9993 rows x 3 columns]